# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('trim_function', models.CharField(max_length=1000)),
                ('map_function', models.CharField(max_length=1000)),
                ('reduce_function', models.CharField(max_length=1000)),
            ],
        ),
    ]
