# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0002_auto_20160608_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dcprocess',
            old_name='name',
            new_name='process_name',
        ),
    ]
