# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0003_auto_20160608_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcprocess',
            name='process_code',
            field=models.CharField(default='11111111111111111111111111111111', max_length=1000),
        ),
    ]
